# Generated by Django 5.0.6 on 2024-07-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='hobbie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
